website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from .models import User, Pro
from sqlalchemy import func, and_, or_, case
from datetime import datetime, timedelta
from . import db, smart

from fhirclient.models.medicationrequest import MedicationRequest
from fhirclient.models.medicationstatement import MedicationStatement
from fhirclient.models.medication import Medication


def get_patient_list():
    latest_pro = (
        db.session.query(Pro.user_id, func.max(Pro.date).label('max_date')) \
            .group_by(Pro.user_id)\
            .subquery()
        )
    
    
    patient_list = db.session.query(User) \
        .filter_by(role_id=1) \
        .join(latest_pro, latest_pro.c.user_id == User.id, isouter=True) \
        .join(Pro, and_(
                Pro.user_id == User.id,
                Pro.date == latest_pro.c.max_date
            ), isouter=True) \
        .with_entities(
            User.id, 
            User.first_name, 
            User.last_name,
            Pro.date,
            case((or_(Pro.hrsn_1>0, Pro.hrsn_2>0), 'House'), else_='').label('sn1'),
            case((Pro.hrsn_3>0, 'Food'), else_='').label('sn2'),
            case((Pro.hrsn_4>0, 'Transportation'), else_='').label('sn3'),
            case((Pro.hrsn_5>0, 'Finance'), else_='').label('sn4'),
            case((Pro.hrsn_6>0, 'Support'), else_='').label('sn5'),
            (sum([Pro.med_1,Pro.med_2,Pro.med_3,Pro.med_4])*5).label('med')
        )
    
    return patient_list


def get_medications(pid):
    search = MedicationStatement.where(struct={'subject':'Patient/'+pid, 'status':'active'})
    med_resources = search.perform_resources(smart.server)
    
    if not med_resources:
        search = MedicationRequest.where(struct={'subject':'Patient/'+pid, 'status':'active'})
        med_resources = search.perform_resources(smart.server)
    
    med_list = set()
    
    for m in med_resources:
        medication = None
        try:
            med_ref = m.medicationReference.reference.split('/')[1]
            medication = Medication.read(med_ref, smart.server).code.coding[0].display
        except:
            pass
        
        if medication:
            med_list.add(medication)
            continue
        else:
            try:
                medication = m.medicationCodeableConcept.coding[0].display
            except:
                continue
        
        if medication:
            med_list.add(medication)
            
    return list(med_list)


views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    if current_user.role_id == 1:
        try:
            last_update = max([pro.date for pro in current_user.pros])
        except:
            last_update = ''
            
        return render_template("patient_home.html", 
                               user=current_user, 
                               last_update=last_update,
                               med_list = get_medications(current_user.pid))
    
    elif current_user.role_id == 2:
        return render_template("provider_home.html", user=current_user, patient_list=get_patient_list())
    
    return render_template("home.html", user=current_user)



@views.route('/prosurvey', methods=['GET','POST'])
@login_required
def pro_survey():
    if request.method == 'POST':
        pro_ans = [
            request.form.get('hrsnQ1'),
            request.form.getlist('hrsnQ2'),
            request.form.get('hrsnQ3'),
            request.form.get('hrsnQ4'),
            request.form.get('hrsnQ5'),
            request.form.get('hrsnQ6'),
            request.form.get('medQ1'),
            request.form.get('medQ2'),
            request.form.get('medQ3'),
            request.form.get('medQ4')
        ]
        
        flag = True
        for i in range(len(pro_ans)):
            if not pro_ans[i]:
                flash('Question '+str(i+1)+' is blank.', category='error')
                flag = False
                break
        
        if flag:
            new_pro_ans = Pro(
                hrsn_1 = int(pro_ans[0]),
                hrsn_2 = sum([int(r) for r in pro_ans[1]]),
                hrsn_3 = int(pro_ans[2]),
                hrsn_4 = int(pro_ans[3]),
                hrsn_5 = int(pro_ans[4]),
                hrsn_6 = int(pro_ans[5]),
                med_1 = int(pro_ans[6]),
                med_2 = int(pro_ans[7]),
                med_3 = int(pro_ans[8]),
                med_4 = int(pro_ans[9]),
                user_id = current_user.id
            )
            db.session.add(new_pro_ans)
            db.session.commit()
            flash('New PRO Survey submitted!', category='success')
            return redirect(url_for('views.home'))
        
    return render_template("proSurvey.html", user=current_user)


@views.route('/patient_info/<id>')
@login_required
def patient_info(id):
    patient = db.session.query(User) \
        .filter_by(id=id) \
        .with_entities(
            User.id, 
            User.first_name, 
            User.last_name,
            User.pid
        ).first()
        
    pro_start_dtm = datetime.today() - timedelta(days = 180)
    
    patient_pro = db.session.query(Pro) \
        .filter(Pro.user_id==id, Pro.date>=pro_start_dtm )\
        .with_entities(
            Pro.date,
            case((or_(Pro.hrsn_1>0, Pro.hrsn_2>0), 'House'), else_='').label('sn1'),
            case((Pro.hrsn_3>0, 'Food'), else_='').label('sn2'),
            case((Pro.hrsn_4>0, 'Transportation'), else_='').label('sn3'),
            case((Pro.hrsn_5>0, 'Finance'), else_='').label('sn4'),
            case((Pro.hrsn_6>0, 'Support'), else_='').label('sn5'),
            (sum([Pro.med_1,Pro.med_2,Pro.med_3,Pro.med_4])*5).label('med')
        )\
        .order_by(Pro.date)
        
    patient_data = {
            'info': patient,
            'medications': get_medications(patient.pid),
            'pro': patient_pro
        }
    
    return render_template('patient_info.html', user=current_user, patient_data = patient_data)

website/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark" style="background-color:#ff7f27">
        <button
            class="navbar-toggler ml-auto"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" id="home" href="/">Home</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container" style="margin-top: 65px; margin-bottom: 65px">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger alter-dismissable fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alter-dismissable fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
        
        {% block content %} {% endblock %}
    </div>
    
    <nav class="navbar fixed-bottom" style="background-color:#ff7f27">
        <span class="navbar-brand mb-0 h1" style="color:white"><b>MY PRO</b></span>
    </nav>
    
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
</body>

</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %} 
<h1>Home Page</h1>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %} 
<form method="POST">
    <h2 align="center">Login</h2>
    <div class="form-group">
         <label for="email">Email Address</label>
         <input
             type="email"
             class="form-control"
             id="email"
             name="email"
             placeholder="Enter email"
         />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter password"
        />
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock %}

website/templates/patient_home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %} 
<h2>Hi, {{user.first_name}}!</h2>
<br></br>
<a class="btn btn-primary" href="/prosurvey" role="button">Submit a New PRO Survey</a>
<p> Last PRO update: 
{% if not last_update %}
    No previous submissions.
{% else %}
    {{last_update}}
{% endif %}
</p>
<br></br>
<h4>Current Medications</h4>
{% if not med_list %}
<p>None.</p>
{% else %}
<ul>
    {% for m in med_list %}<li>{{m}}</li>{% endfor %}
</ul> 
{% endif %}
{% endblock %}

website/templates/patient_info.html
{% extends "base.html" %} {% block title %}Patient Detail{% endblock %}

{% block content %}
<a class="btn btn-primary" href="/" role="button">Back to Patient List</a>
<p> </p>
<h4>Patient Information</h4> 
<p><b>First Name:</b> {{ patient_data['info'].first_name }}</p>
<p><b>Last Name:</b> {{ patient_data['info'].last_name }}</p>
<p><b>PID:</b> {{ patient_data['info'].pid }}</p>
<p> </p>
<h4>Current Medications</h4>
{% if not patient_data['medications'] %}
<p>None.</p>
{% else %}
<ul>
    {% for m in patient_data['medications'] %}<li>{{m}}</li>{% endfor %}
</ul> 
{% endif %}
<p> </p>
<h4>PRO within 180 Days</h4>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">PRO Date</th>
        <th scope="col">Social Needs</th>
        <th scope="col">Self-Efficacy</th>
    </tr>
    </thead>
    <tbody>
    {% for pro in patient_data['pro']: %}
    <tr>
        <td scope="row">{{pro.date}}</td>
        <td>
            {% for sn in [pro.sn1, pro.sn2, pro.sn3, pro.sn4, pro.sn5]: %}
                {% if sn %}{{sn}} {% endif %}
            {% endfor %}
        </td>
        <td>{{pro.med}}%</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<p> </p>
<a class="btn btn-primary" href="/" role="button">Back to Patient List</a>
{% endblock %}

website/templates/provider_home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %}
<h2>Patient List</h2>
Click patient id # to get patient details.
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Last PRO Update</th>
        <th scope="col">Social Needs</th>
        <th scope="col">Self-Efficacy</th>
    </tr>
    </thead>
    <tbody>
    {% for p in patient_list: %}
    <tr>
        <th scope="row">
            <a href="{{url_for('views.patient_info', id=p.id)}}">{{p.id}}</a>
        </th>
        <td>{{p.first_name}}</td>
        <td>{{p.last_name}}</td>
        <td>{{p.date}}</td>
        <td>
            {% for sn in [p.sn1, p.sn2, p.sn3, p.sn4, p.sn5]: %}
                {% if sn %}{{sn}} {% endif %}
            {% endfor %}
        </td>
        <td>{% if p.med %}{{p.med}}%{% endif %}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

website/templates/signUp.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %} 
<form method="POST">
    <h2 align="center">Sign Up</h2>
    <div class="form-group">
         <label for="email">Email Address</label>
         <input
             type="email"
             class="form-control"
             id="email"
             name="email"
             placeholder="Enter email"
         />
    </div>
    <div class="row">
        <div class="form-group col">
            <label for="firstName">First Name</label>
            <input
                type="text"
                class="form-control"
                id="firstName"
                name="firstName"
                placeholder="First Name"
            />
        </div>
        <div class="form-group col">
            <label for="lastName">Last Name</label>
            <input
                type="text"
                class="form-control"
                id="lastName"
                name="lastName"
                placeholder="Last Name"
            />
        </div>
    </div>
    <div class="row">
        <div class="form-group col">
            <label for="birthday">Date of Birth</label>
            <input
                type="text"
                class="form-control"
                id="birthday"
                name="birthday"
                placeholder="yyyy-mm-dd"
            />
        </div>
        <div class="form-group col">
            <label for="ID">ID #</label>
            <input
                type="text"
                class="form-control"
                id="ID"
                name="ID"
                placeholder="ID number provided by your healthcare facility"
            />
        </div>
    </div>
    <div class="row">
        <div class="form-group col">
            <label for="password1">Password</label>
            <input
                type="password"
                class="form-control"
                id="password1"
                name="password1"
                placeholder="Enter password"
            />
        </div>
        <div class="form-group col">
            <label for="password2">Password (Confirm)</label>
            <input
                type="password"
                class="form-control"
                id="password2"
                name="password2"
                placeholder="Confirm password"
            />
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    
</form>

{% endblock %}